version: '3.1'
services:
  backend:
    container_name: g2g-backend
    build: ./g2g-backend/
    ports:
      - "6000:3000"
    volumes:
      - ./g2g-backend:/usr/src/app
  frontend:
    container_name: g2g-frontend
    build: ./g2g-frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./g2g-frontend:/usr/src/app
    depends_on:
      - backend
